// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using todo_web_app2.Models;

#nullable disable

namespace todo_web_app2.Migrations
{
    [DbContext(typeof(PersonContext))]
    partial class PersonContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("todo_web_app2.Models.Devices", b =>
                {
                    b.Property<int>("device_Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("device_Id"));

                    b.Property<string>("device_Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("device_Id");

                    b.ToTable("tbl_Device");
                });

            modelBuilder.Entity("todo_web_app2.Models.Person", b =>
                {
                    b.Property<int>("person_Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("person_Id"));

                    b.Property<int>("dev_Id")
                        .HasColumnType("integer");

                    b.Property<bool>("is_Active")
                        .HasColumnType("boolean");

                    b.Property<string>("person_Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("person_Id");

                    b.ToTable("tbl_Person");
                });
#pragma warning restore 612, 618
        }
    }
}
